export interface ToolCall {
  /**
   * Identifier generated by the LLM provider
   * for this particular tool invocation.
   */
  id: string;

  /**
   * Name of the requested tool.
   *
   * Example:
   * "filesystem.read"
   * "code.search"
   */
  name: string;

  /**
   * Arguments generated by the LLM.
   *
   * They are intentionally unknown here because
   * they have not been validated yet.
   */
  arguments: unknown;
}